---
title: "Missing variables"
author: "Claudius Gräbner"
date: "23 5 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Missing variables

## General

* EU member
* WU member
* HBOOM

## KOF Variables


## Barro-Lee (ggf auch WB)

* Years of schooling
* Percent of people with secondary and tertiary education

## EU KLEMS
* Share of finance: employment, gross output, value added

## IMF

* World GDP growth
* Real Effective Exchange rate

## Missing from WDI

* FDI to GDP
* Tax revenues to GDP
* Imports to GDP
* Exports to GDP
* Trade to GDP
* RD costs
* WTS
# CTS
* WTS Pop
* Lietal
* Alcala
* Frankel

Dann die WGI indicators:
* Control of curroption
* Government effectiveness
* Role of Law
* Political stability

## Missinhg from OECD

* Unemployment statistics
* Long-term interest rate
* Relative CPI
* Tax revenue composition
* Employment protection
* Tax wedge
* Minimum wage
* Housing: RPPI data file
* HPI: house price stuff
* Union density
* ICT investment


## ISD variables
Einfach nochmal checken welche wir da nehmen.

## Chinn-Ito

* Capital openness

## ICTWSS Data

## Eurostat

* Gov expenditure on education
* Gov expenditure on healthcare
* Gov expenditure on social protection
* Industrial output (and maybe others?)

## Lane-Milesi Data
One FDI etc,

# Open Questions

Should we include the Jorgensen/Wu dataset?
